singleQuote: true
bracketSpacing: true
arrowParens: always
printWidth: 120
singleAttributePerLine: true
tabWidth: 2
useTabs: false
semi: true
trailingComma: all
proseWrap: preserve
endOfLine: auto
quoteProps: preserve
overrides:
  - files: '*.scss'
    options:
      singleQuote: false
