DROP DATABASE IF EXISTS testhp;
CREATE DATABASE IF NOT EXISTS testhp;
SHOW CREATE DATABASE testhp;
USE testhp;

CREATE USER adm@localhost IDENTIFIED BY 'adm!23';
GRANT ALL ON testhp.* TO adm@localhost;

DROP TABLE IF EXISTS houses;
CREATE TABLE houses (
    id SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    UK JSON,
    EN JSON,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS spells;
CREATE TABLE spells (
    id SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    UK JSON,
    EN JSON,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS students;
CREATE TABLE students (
    id SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    UK JSON,
    EN JSON,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS stuff;
CREATE TABLE stuff (
    id SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    UK JSON,
    EN JSON,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
