export interface Student {
  name: string;
  portrait: string;
  house: string;
  description: string;
  interestingFacts: string[];
}

export const StudentsEN: Student[] = [
  {
    name: 'Harry Potter',
    portrait: '',
    house: 'Griffindor',
    description: 'Main character, student at Hogwarts, co-founder and first leader of Dumbledore`s Army',
    interestingFacts: [
      'Achieves an Outstanding Defence Against the Dark Arts O.W.L., something that not even Hermione achieved',
      'Still the only wizard to this day that has had all three Unforgivable Curses cast on him and survived',
      'Has the last line in many of the books, and if not, he makes the last gesture',
      'Despite being a talented Quidditch player (and the team Seeker, considered the most important player on the team), Harry never played a full season (every minute of all three matches)',
    ],
  },
  {
    name: 'Hermione Granger',
    portrait: '',
    house: 'Griffindor',
    description: 'Muggle-born student in Harry`s year, one of his best friends',
    interestingFacts: [
      'Received an Outstanding in all of her O.W.L`s except for her Defense Against the Dark Arts O.W.L, and has aced many exams in the past by more than 100%',
      'Cries in seven of the eight films',
      'The only spell Hermione ever had trouble with was the Patronus Charm',
      'Hermione`s wand wood of vine corresponds to her birthday in the Celtic calendar',
    ],
  },
  {
    name: 'Ron Weasley',
    portrait: '',
    house: 'Griffindor',
    description: 'Youngest son of Arthur and Molly Weasley who is best friends with Harry Potter and Hermione Granger',
    interestingFacts: [
      'Has used three wands during the stories',
      'His favourite sandwich type is bacon, and his least favourite is corned beef',
      'In the films, Ron is well known for using the phrase "Bloody hell" when he is surprised or frightened',
      'He is the only known pure-blood wizard who obtains a Muggle driving licence',
    ],
  },
  {
    name: 'Draco Malfoy',
    portrait: '',
    house: 'Slytherin',
    description: 'Student in Harry`s year',
    interestingFacts: [
      'Never referred to Ron or Hermione by their first names during the course of the original seven books. He did, however, by the events of The Cursed Child',
      'Seems to have a fondness for green apples, since he is seen eating one in Prisoner of Azkaban and putting one in the vanishing cabinet in Half-Blood Prince',
      'It is shown that he is somewhat more respectful in the films than the books',
      'Draco would have attended Durmstrang Institute, a school that does not admit Muggle-borns and teaches the Dark Arts, but his mother didn`t want him staying so far away from home',
    ],
  },
  {
    name: 'Gregory Goyle',
    portrait: '',
    house: 'Slytherin',
    description: 'Student in Harry`s year',
    interestingFacts: [
      'Was one of the Beaters for the Slytherin Quidditch team, but he was chosen for his size and strength rather than skill',
      'Was able to perform the Unforgivable Curses and was particularly skilled in the casting of the Cruciatus Curse. Neville noted that because of his proficiency with the curse, it was probably the first time he had been top in anything',
    ],
  },
  {
    name: 'Neville Longbottom',
    portrait: '',
    house: 'Griffindor',
    description: 'Student in Harry`s year',
    interestingFacts: [
      'Appeared to suffer from a degree of post-traumatic stress disorder. This was likely due to his parents being subjected to the curse`s worst possible outcome: the onset of permanent and complete insanity',
      'Destroyed the seventh and final Horcrux when he beheaded the snake Nagini',
      'In the film, Neville is shown to be quite good at dancing, being one of the very last to leave the ball. However, in the novel, he is shown to be quite bad, stepping on Ginny`s toes numerous times',
    ],
  },
  {
    name: 'Ginny Weasley',
    portrait: '',
    house: 'Griffindor',
    description: 'Student one year below Harry. Only daughter and youngest child of Arthur and Molly Weasley',
    interestingFacts: [
      'Many fans believed that `Ginny` was short for `Virginia`. It was later established that Ginny`s given name is `Ginevra`',
      'Her wand was made from yew, as the Voldemort`s one',
      'She was the first girl to arrive in the Weasley family in generations',
      'Was popular during their time at Hogwarts, and was fancied by numerous boys. Her brothers: Fred, George, and Ron, often thought that she was too popular',
    ],
  },
  {
    name: 'Luna Lovegood',
    portrait: '',
    house: 'Griffindor',
    description: 'Student one year below Harry.',
    interestingFacts: [
      'The only one of Harry`s close school friends who is not a fellow Gryffindor and the only person still living to give their name to one of Harry`s children',
      'In the early drafts, Luna`s name was "Lily Moon", until Rowling changed it. She is the only known member of the Lovegood family whose first name is not of Greek origin, rather it is of Latin origin',
      'Her possessions were often stolen by some other pupils and hidden, with the all her shoes. Luna often had to walk around barefoot because of this',
    ],
  },
  {
    name: 'Seamus Finnigan',
    portrait: '',
    house: 'Griffindor',
    description: 'Student in Harry`s year',
    interestingFacts: [
      'Keeps setting things on fire and causing them to explode',
      'During Seamus`s final year at Hogwarts, his face had been battered and bruised by the Carrows to an extent that neither Harry nor Dean Thomas could recognise him, until he spoke with his distinct Irish accent',
      'Seamus has been played by Devon Murray, he does not fit the physical description, but he does have the Irish accent needed for the role',
    ],
  },
  {
    name: 'Hannah Abbott',
    portrait: '',
    house: 'Hufflepuff',
    description: 'Student in Harry`s year',
    interestingFacts: [
      'Since Hannah`s surname, Abbott, was the first alphabetically, she was the first new student of those to arrive at Hogwarts to be sorted into her house during the Welcoming Feast',
      'Later in life, Hannah married fellow classmate Neville Longbottom and became landlady of the Leaky Cauldron, which the couple lived above. She eventually trained as a healer and applied for the job of Matron at Hogwarts',
    ],
  },
  {
    name: 'Pansy Parkinson',
    portrait: '',
    house: 'Slytherin',
    description: 'Student in Harry`s year',
    interestingFacts: [
      'She fawned over her fellow housemate, Draco Malfoy, was a member of his gang, and possibly developed a romantic relationship with him',
      'J. K. Rowling has said that Pansy did not end up marrying Draco because Rowling always hated her: `She`s every girl who ever teased me at school. She`s the Anti-Hermione. I loathe her`',
      'Pansy frequently taunted others about their physical appearances, and also tended to take great amusement in seeing others publicly embarrassed or hurt',
    ],
  },
  {
    name: 'Vincent Crabbe',
    portrait: '',
    house: 'Slytherin',
    description: 'Student in Harry`s year',
    interestingFacts: [
      'Despite his large frame, Crabbe had a surprisingly soft voice, though he speaks so rarely that Harry never noted his tone of voice until his last battle',
      'During the Battle of Hogwarts, he accidentally killed himself using Fiendfyre',
      'In the books, Crabbe is generally portrayed as being more intelligent than Goyle but in the films, it seems to be the other way around',
    ],
  },
  {
    name: 'Blaise Zabini',
    portrait: '',
    house: 'Slytherin',
    description: 'Student in Harry`s year',
    interestingFacts: [
      'Was the son of a famously beautiful witch who had been widowed seven times. Each husband`s death occurred both under suspicious circumstances and left the already wealthy Ms. Zabini and her son with more money',
      'Given his surname and his ethnicity, it is likely that Zabini is of (at least partial) Italian and African descent',
      'Blaise seemed to be a highly arrogant individual, who looked down on nearly everyone and everything',
    ],
  },
  {
    name: 'Dean Thomas',
    portrait: '',
    house: 'Griffindor',
    description: 'Student in Harry`s year',
    interestingFacts: [
      'Was even taller than Ron Weasley due to the fact that he had a long neck',
      'Dean appeared to be very artistic and was said to be `good with a quill`',
      'Having been an avid fan of the Muggle sport of Football, Dean owned the ball used in the playing of this game',
      'During Harry`s time in school, Dean is the only male Chaser on the Gryffindor Quidditch Team',
    ],
  },
  {
    name: 'Ernie Macmillan',
    portrait: '',
    house: 'Hufflepuff',
    description: 'Student in Harry`s year',
    interestingFacts: [
      'He was the only Hufflepuff in his year who advanced to N.E.W.T.-level',
      'Ernie is likely full or part Scottish, as his surname of Macmillan is a fairly common Scottish surname',
      'Ernie was born into a pure-blood family that could trace its lineage back nine generations',
    ],
  },
  {
    name: 'Lavender Brown',
    portrait: '',
    house: 'Griffindor',
    description: 'Student in Harry`s year',
    interestingFacts: [
      'Lavender was a somewhat silly and sentimental girl. She gave the name of "Won-Won" for Ron and sent him a necklace for Christmas saying "My Sweetheart" on it',
      'She seemed to have a reasonably close and caring relationship with Divination professor Sybill Trelawney, had an unwavering faith in the reliability of Trelawney`s predictions ',
    ],
  },
  {
    name: 'Parvati Patil',
    portrait: '',
    house: 'Griffindor',
    description: 'Student in Harry`s year',
    interestingFacts: [
      'Padma`s identical twin sister',
      'Parvati could be seen as the less serious of the Patil twins; like her friend Lavender Brown, she enjoyed gossip and fashion, and the two were often seen whispering and giggling together',
      'In the film adaptation, Parvati is shown to spend a lot of time with her twin. However, in the books, she is seldom seen without her best friend, Lavender',
    ],
  },
  {
    name: 'Padma Patil',
    portrait: '',
    house: 'Ravenclaw',
    description: 'Student in Harry`s year',
    interestingFacts: [
      'Parvati`s identical twin sister',
      'Padma seemed to be the less outgoing and more studious of the twins. She was also much quieter than her sister.',
      'In the film adaptation, Padma is shown to be in Gryffindor along with Parvati, instead of Ravenclaw, because the director feared that audience wouldn`t understand that the Patils were sisters',
    ],
  },
  {
    name: 'Cormac McLaggen',
    portrait: '',
    house: 'Griffindor',
    description: 'Student one year above Harry',
    interestingFacts: [
      'McLaggen was a poor team player and a poor Quidditch Keeper. He spent much more time in the match offering unwanted observations of others rather than playing',
      'Aggressive, arrogant, and self-righteous: McLaggen epitomised the most negative aspects of the stereotypical Gryffindor characteristics',
      'His family known for being "big in the Ministry", so he is good friends with many influential wizards, like the Minister of Magic, Rufus Scrimgeour and Bertie Higgs',
    ],
  },
  {
    name: 'Cho Chang',
    portrait: '',
    house: 'Ravenclaw',
    description: 'Student one year above Harry',
    interestingFacts: [
      'Because of her beauty, she attracted a considerable amount of male attention during her Hogwarts years, most notably: Cedric Diggory, Roger Davies, Michael Corner, and of course Harry',
      'In Chinese, chóu chàng means "melancholy". This may allude to Cho`s fragile emotional state following Cedric Diggory`s murder',
      'Later married a Muggle individual',
    ],
  },
  {
    name: 'Justin Finch-Fletchley',
    portrait: '',
    house: 'Hufflepuff',
    description: 'Student in Harry`s year',
    interestingFacts: [
      'His behaviour was outgoing, talkative, cheerful, and friendly. He seemed a little naive and easily impressed and influenced by others; for instance, he believed all of Gilderoy Lockhart`s fabricated tales and admired him greatly',
      'It is interesting to note that the trio formed by Ernie, Hannah and Justin is quite similar to the trio formed by Harry, Ron and Hermione',
    ],
  },
  {
    name: 'Cedric Diggory',
    portrait: '',
    house: 'Hufflepuff',
    description: 'Student two years above Harry',
    interestingFacts: [
      'Cedric was said to be an embodiment of the qualities of Hufflepuff House. He had a sense of fair play and his ability to accept there were those who were better than him is a definite testament to his nobility and his grace',
      'Co-winner of the Triwizard Tournament',
      'Cedric`s death is the first death Harry witnesses and this allowed him to see thestrals later',
    ],
  },
  {
    name: 'Oliver Wood',
    portrait: '',
    house: 'Griffindor',
    description: 'Student four years above Harry',
    interestingFacts: [
      'Captain and Keeper of the Quidditch team. He was known to get a maniacal look in his eyes when he was enthusing about Quidditch',
      'Though Oliver was not a member of Dumbledore`s Army, having left Hogwarts two years before its formation, Wood fought with D.A. members in the Battle of Hogwarts',
    ],
  },
  {
    name: 'Fred Weasley',
    portrait: '',
    house: 'Griffindor',
    description: 'Student, Son of Arthur and Molly Weasley',
    interestingFacts: [
      'Identical twin brother of George Weasley. Fred was born first. The books never mention this, however, Rowling solved the mystery on Twitter',
      'The twins invented their own nicknames at age five, after their mother gave them the wrong sweaters for Christmas',
      'Fred`s name is the last word Bellatrix pronounces',
      'His brother George named his son in honour of him',
    ],
  },
  {
    name: 'George Weasley',
    portrait: '',
    house: 'Griffindor',
    description: 'Student, Son of Arthur and Molly Weasley',
    interestingFacts: [
      'Identical twin brother of Fred Weasley. While both twins have an inventive and effervescent personalities, George always seems to be following his older brother',
      'George was more effective Quidditch player, managing to hit a Bludger six times in Quidditch scenes',
      'They`re the only Weasley brothers who don`t become prefects',
      'Married Angelina Johnson after the Second Wizarding War. They had two children',
    ],
  },
  {
    name: 'Romilda Vane',
    portrait: '',
    house: 'Griffindor',
    description: 'Student in Harry`s year',
    interestingFacts: [
      'Was obsessively in love with Harry Potter and envious of his close relationship with friends',
      'Seemed to represent all the stereotypical aspects of Gryffindor house, both positive and negative',
      'Owned a music box topped with a ballet troll',
      'Nothing much is known about her personality in the films partly due to the fact that she has no lines in any of the films she appears in',
    ],
  },
  {
    name: 'Zacharias Smith',
    portrait: '',
    house: 'Hufflepuff',
    description: 'Student in Harry`s year',
    interestingFacts: [
      'The Sorting Hat sensed that Smith didn`t possess any of the qualities needed for the other houses and put him in Hufflepuff by default, since Helga Hufflepuff would take students that were not picked by the other founders',
      'Zacharias Smith seems to be more pleasant in the movies than in the novels',
      'Hermione considered asking Smith to Slughorn`s Christmas party instead of Cormac McLaggen, as she knew that Ron loathed both boys',
    ],
  },
  {
    name: 'Lee Jordan',
    portrait: '',
    house: 'Gryffindor',
    description: 'Student two years above Harry',
    interestingFacts: [
      'Lee was a humorous and comedic individual, much to the annoyance of Professor McGonagall who was embarrassed by his commentaries during Quidditch games',
      'After Hogwarts, he hosted a radio show, Potterwatch, in order to inform and encourage the wizarding world, advising how they could all be protected from Lord Voldemort',
    ],
  },
  {
    name: 'Marietta Edgecombe',
    portrait: '',
    house: 'Ravenclaw',
    description: 'Student one year above Harry',
    interestingFacts: [
      'Her mother was a Ministry employee and as such, Marietta felt strong pressure to be on Umbridge`s good side',
      'After she was struck with the parchment jinx for betraying the Dumbledore`s Army, she bore pimples spelling "SNEAK" across her face',
      'In the film adaptation, Marietta is absent, and Cho Chang is the one who "betrayed". whilst under the effects of Veritaserum',
    ],
  },
  {
    name: 'Colin Creevey',
    portrait: '',
    house: 'Gryffindor',
    description: 'Student one year below Harry',
    interestingFacts: [
      'He always took pictures in his first year, which could lead to him being often annoying. This was partly due to him taking pictures at inopportune moments',
      'During his first year at Hogwarts, although he and Harry were not so close, Colin thought that he was Harry`s best friend',
    ],
  },
];

export const StudentsUA: Student[] = [
  {
    name: 'Гаррі Поттер',
    portrait: '',
    house: 'Ґрифіндор',
    description: 'Головний персонаж, студент Гоґвортсу, співзасновник та лідер Дамблдорової Армії',
    interestingFacts: [
      'Досягає найвищої оцінки на іспиті СОВ з захисту від темних мистецтв, чого не досягла навіть Герміона',
      'Досі єдиний чарівник, який вижив після накладення на нього всіх трьох Непрощенних проклять',
      'Має останню фразу в багатьох книгах, якщо ні, він робить останню дію',
      'Незважаючи на те, що Гаррі був талановитим гравцем у Квідич (і Шукачем, роль якого вважають найважливішою у команді), Гаррі ніколи не грав повний сезон (кожну хвилину всіх трьох матчів)',
    ],
  },
  {
    name: 'Герміона Ґрейнджер',
    portrait: '',
    house: 'Ґрифіндор',
    description: 'Однокурсниця Гаррі, одна з його найкращих друзів',
    interestingFacts: [
      'Досягає найвищої оцінки у всіх іспитах СОВ, окрім захисту від темних мистецтв, і склала багато іспитів у минулому більш ніж на 100%',
      'Плаче в семи з восьми фільмів',
      'Єдине заклинання, з яким Герміона коли-небудь мала проблеми, це чари Патронуса',
      'Виноградна паличка Герміони відповідає її дню народження за кельтським календарем',
    ],
  },
  {
    name: 'Рон Візлі',
    portrait: '',
    house: 'Ґрифіндор',
    description: 'Однокурсник Гаррі, один з його найкращих друзів',
    interestingFacts: [
      'Впродовж історії має аж три чарівні пальчки',
      'Його улюблений сендвіч - з беконом, а найменш улюблений - з солониною',
      'У фільмах, Рон добре відомий тим, що вживає фразу «Прокляття», коли він здивований або наляканий',
      'Він єдиний відомий чистокровний чарівник, який отримав маглівські водійські права',
    ],
  },
  {
    name: 'Драко Мелфой',
    portrait: '',
    house: 'Слизерин',
    description: 'Однокурсник Гаррі',
    interestingFacts: [
      'Ніколи не називав Рона чи Герміону їхніми іменами протягом оригінальних семи книг. Однак він це зробив через події «Проклятого дитяти»',
      'Схоже, він любить зелені яблука, оскільки він їсть одне у «В’язні Азкабану» та кладе одне у зникаючу шафу у «Напівкровному принці»',
      'У фільмах він показаний дещо з кращою людиною, аніж у книгах',
      'Драко відвідував би Інститут Дурмстранг, школу, де не приймають маглонароджених і навчають темним мистецтвам, але його мати не хотіла, щоб він залишався так далеко від дому',
    ],
  },
  {
    name: 'Грегорі Гойл',
    portrait: '',
    house: 'Слизерин',
    description: 'Однокурсник Гаррі',
    interestingFacts: [
      'Був одним із Забивачів команди Слизерина з Квідичу, але його обрали за його розмір і силу, а не за майстерність',
      'Зміг виконувати Непрощенні закляття та був особливо вправним у застосуванні закляття Круціатус. Невілл зауважив, що через дану його майстерність це був, ймовірно, перший раз, коли він був найкращим у чомусь',
    ],
  },
  {
    name: 'Невіл Лонґботом',
    portrait: '',
    house: 'Ґрифіндор',
    description: 'Однокурсник Гаррі',
    interestingFacts: [
      'Схоже, що він страждає від посттравматичного стресового розладу. Ймовірно, це сталося через те, що його батьки піддалися одному з найгірших результатів заклять: настанню незворотного повного божевілля',
      'Знищив сьомий і останній горокракс, коли обезголовив змію Наджіні',
      'У фільмі показано, що Невілл досить добре танцює, будучи одним з останніх, хто залишає бал. Однак у книгах це не так',
    ],
  },
  {
    name: 'Джіні Візлі',
    portrait: '',
    house: 'Ґрифіндор',
    description: 'Учениця на рік молодше Гаррі. Єдина дочка і наймолодша дитина Артура та Моллі Візлі',
    interestingFacts: [
      'Багато шанувальників вважали, що "Джінні" - це скорочення від "Вірджинія". Пізніше було встановлено, що ім`я Джінні - «Джіневра»',
      'Її паличка була зроблена з тиса, як і паличка Волдеморта',
      'Вона була першою дівчинкою, яка народилась в родині Візлі за кілька поколінь',
      'Досить популярна в Гоґвортсі, і її любили численні хлопці. Її брати: Фред, Джордж і Рон часто вважали її занадто популярною',
    ],
  },
  {
    name: 'Луна Лавґуд',
    portrait: '',
    house: 'Ґрифіндор',
    description: 'Учениця на рік молодше Гаррі',
    interestingFacts: [
      'Єдина з близьких шкільних друзів Гаррі не з Ґрифіндору, і єдина жива людина, чиїм їм`ям він назвав свою дитину',
      'У перших варіантах книг і`мя Луни було "Лілі Мун", поки Роулінг не змінила його. Вона єдиний відомий член родини Лавґудів, чиє ім`я не грецького, а латинського походження',
      'Її майно часто викрадали інші учні та ховали разом із усім її взуттям. Через це Луні часто доводилося ходити босоніж',
    ],
  },
  {
    name: 'Шеймус Фініґан',
    portrait: '',
    house: 'Ґрифіндор',
    description: 'Однокурсник Гаррі',
    interestingFacts: [
      'Постійно підпалює речі та призводить до їх вибухання',
      'Смертежери Керроу побили його обличчя до такої міри, що ані Гаррі, ані Дін Томас не могли його впізнати, поки він не заговорив зі своїм виразним ірландським акцентом',
      'Шеймуса зіграв Девон Мюррей, він не відповідає фізичному опису, але у нього є ірландський акцент, необхідний для ролі',
    ],
  },
  {
    name: 'Анна Ебот',
    portrait: '',
    house: 'Гафелпаф',
    description: 'Однокурсниця Гаррі',
    interestingFacts: [
      'Оскільки прізвище Анни, Ебот, було першим за алфавітом, вона була першим новим учнем із тих, хто прибув до Гоґвортсу і був розсортований у свій гуртожиток під час Вітального бенкету',
      'Пізніше Анна вийшла заміж за свого однокласника Невіла Лонґботома і стала господинею Дірявого казана, над яким подружжя жило. Згодом вона отримала освіту цілительки та подала заявку на роботу медсестри в Гоґвортсі',
    ],
  },
  {
    name: 'Пенсі Паркінсон',
    portrait: '',
    house: 'Слизерин',
    description: 'Однокурсниця Гаррі',
    interestingFacts: [
      'Вона підлещувалася до Драко Мелфоя, була членом його банди і, можливо, була з ним в романтичних стосунках',
      'Роулінг сказала, що Пенсі не вийшла заміж за Драко, тому що Роулінг завжди її ненавиділа: "Вона — кожна дівчина, яка коли-небудь дражнила мене в школі. Вона АнтиГерміона. Я її ненавиджу"',
      'Пансі часто кепкувала над іншими з приводу їхнього зовнішнього вигляду, а також, як правило, дуже веселилася, бачачи, як інших публічно ображали',
    ],
  },
  {
    name: 'Вінсент Креб',
    portrait: '',
    house: 'Слизерин',
    description: 'Однокурсник Гаррі',
    interestingFacts: [
      'Незважаючи на велику статуру, у Креба був напрочуд м’який голос, хоча він розмовляв настільки рідко, що Гаррі ніколи не помічав його тону до останньої битви',
      'Під час битви за Гоґвортс він випадково вбив себе за допомогою Зложару',
      'У книгах Креба зазвичай зображують розумнішим за Ґойла, але у фільмах все виглядає навпаки',
    ],
  },
  {
    name: 'Блез Забіні',
    portrait: '',
    house: 'Слизерин',
    description: 'Однокурсник Гаррі',
    interestingFacts: [
      'Був сином знаменитої вродливої відьми, яка овдовіла сім разів. Смерть усіх чоловіків сталася за підозрілих обставин, а пані Забіні та її син отримували ще більше більше грошей',
      'Враховуючи його прізвище та етнічну приналежність, ймовірно, що Забіні має (принаймні частково) італійське та африканське походження',
      'Блез був дуже зарозумілою людиною, яка дивилася зверхньо майже на всіх і на все',
    ],
  },
  {
    name: 'Дін Томас',
    portrait: '',
    house: 'Ґрифіндор',
    description: 'Однокурсник Гаррі',
    interestingFacts: [
      'Був навіть вище Рона Візлі через те, що мав довгу шию',
      'Дін виявився дуже артистичним і, як кажуть, «добре володів пером»',
      'Будучи пристрасним шанувальником маґлівського футболу, Дін мав м’яч, який використовувався для цієї гри',
      'Під час навчання Гаррі в школі Дін був єдиним Переслідувачем у команді Ґрифіндору з Квідичу',
    ],
  },
  {
    name: 'Ерні Макмілан',
    portrait: '',
    house: 'Гафелпаф',
    description: 'Однокурсник Гаррі',
    interestingFacts: [
      'Він був єдиним серед однокласників з Гафелпаф, який пройшов іспити рівня НОЧІ',
      'Ймовірно, Ерні повністю або частково шотландець, оскільки його прізвище Макміллан є досить поширеним шотландським прізвищем',
      'Ерні народився в чистокровній родині, яка веде свій родовід до дев’ять поколінь',
    ],
  },
  {
    name: 'Лаванда Браун',
    portrait: '',
    house: 'Ґрифіндор',
    description: 'Однокурсниця Гаррі',
    interestingFacts: [
      'Лаванда була дещо дурною і сентиментальною дівчиною. Вона називала Рона "Вон-Вон" і надіслала йому на Різдво намисто з написом "Мій милий"',
      'Вона мала досить близькі та дбайливі стосунки з професором ворожіння Сібілою Трелоні, непохитно вірила в надійність передбачень Трелоні',
    ],
  },
  {
    name: 'Парваті Патіл',
    portrait: '',
    house: 'Ґрифіндор',
    description: 'Однокурсниця Гаррі',
    interestingFacts: [
      'Парваті можна було вважати менш серйозною з близнюків Патіл; як і її подруга Лаванда Браун, вона насолоджувалася плітками та модою, і їх часто бачили, як вони перешіптувалися та хихотіли разом',
      'В екранізації показано, що Парваті проводить багато часу зі своєю сестрою Падмою. Однак у книгах її рідко можна побачити без найкращої подруги Лаванди',
    ],
  },
  {
    name: 'Падма Патіл',
    portrait: '',
    house: 'Рейвенклов',
    description: 'Однокурсниця Гаррі',
    interestingFacts: [
      'Здавалося, Падма була менш комунікабельною та більш старанною з близнюків. Вона також була набагато тихішою за свою сестру',
      'В екранізації Падма показана в Ґрифіндорі разом із Парваті, а не з Рейвенклов, оскільки режисер боявся, що глядачі не зрозуміють, що Патіл були сестрами',
    ],
  },
  {
    name: 'Кормак МакЛагген',
    portrait: '',
    house: 'Ґрифіндор',
    description: 'Учень на один рік старше Гаррі',
    interestingFacts: [
      'МакЛагген був поганим командним гравцем і поганим воротарем з квідичу. Він провів набагато більше часу в матчі, пропонуючи небажані поради іншим, а не граючи',
      'Агресивний, зарозумілий і самовдоволений: МакЛагген втілив найбільш негативні аспекти стереотипних характеристик Ґрифіндору',
      'Його сім`я відома тим, що має «великі чини в Міністерстві», тому він має друзів серед впливових чарівників, таких як Міністр магії Руфус Скрімджер і Берті Хіггс',
    ],
  },
  {
    name: 'Чо Чанґ',
    portrait: '',
    house: 'Ґрифіндор',
    description: 'Учениця на один рік старше Гаррі',
    interestingFacts: [
      'Завдяки своїй красі вона привернула значну кількість чоловічої уваги під час навчання в Гоґвартсі, а саме: Седрик Діґорі, Роджер Девіс, Майкл Корнер і, звичайно, Гаррі',
      'Китайською мовою chóu chàng означає «меланхолія». Це може натякати на крихкий емоційний стан Чо після вбивства Седрика Діґорі',
      'Пізніше вийшла заміж за магла',
    ],
  },
  {
    name: 'Джастін Фінч-Флечлі',
    portrait: '',
    house: 'Гафелпаф',
    description: 'Однокурсник Гаррі',
    interestingFacts: [
      'Він був комунікабельним, балакучим, веселим та доброзичливим. Він здавався трохи наївним, і на нього легко впливали інші. Наприклад, він вірив усім вигаданим казкам Гілдероя Локхарта і дуже захоплювався ним',
      'Цікаво відзначити, що тріо Ерні, Анни та Джастіна дуже схоже на тріо Гаррі, Рона та Герміони',
    ],
  },
  {
    name: 'Седрик Діґорі',
    portrait: '',
    house: 'Гафелпаф',
    description: 'Учень на два роки старше Гаррі',
    interestingFacts: [
      'Седрик був справжнім втіленням якостей дому Гафелпаф. Він мав почуття чесної гри, і його здатність приймати тих, хто був кращим за нього, є очевидним свідченням його благородства',
      'Один з переможців Тричаклунського турніру',
      'Смерть Седріка — перша смерть, свідком якої став Гаррі, і це дозволило йому пізніше побачити тестралів',
    ],
  },
  {
    name: 'Олівер Вуд',
    portrait: '',
    house: 'Ґрифіндор',
    description: 'Учень на чотири роки старше Гаррі',
    interestingFacts: [
      'Капітан і Воротар команди з Квідичу. Відомий тим, що мав маніакальний вираз в очах, коли справа стосувалась Квідичу',
      'Хоча Олівер не був членом Дамблдорової армії, покинувши Гоґвортс за два роки до його створення, воював разом з учасниками битви за Гоґвортс',
    ],
  },
  {
    name: 'Фред Візлі',
    portrait: '',
    house: 'Ґрифіндор',
    description: 'Учень на два роки старше Гаррі',
    interestingFacts: [
      'Брат-близнюк Джорджа Візлі. Фред народився першим. У книгах про це ніколи не згадується, однак Роулінг розкрила цю таємницю в своєму Твітері',
      'Близнюки вигадали собі прізвиська у п`ять років після того, як мати подарувала їм не ті светри на Різдво',
      'Ім`я Фреда - останнє слово, яке вимовляє Белатриса',
      'Його брат Джордж назвав сина на його честь',
    ],
  },
  {
    name: 'Джордж Візлі',
    portrait: '',
    house: 'Ґрифіндор',
    description: 'Учень на два роки старше Гаррі',
    interestingFacts: [
      'Брат-близнюк Фреда Візлі. Незважаючи на те, що обидва близнюки мають винахідливі та яскраві характери, Джордж завжди наслідує свого старшого брата',
      'Джордж був ефективнішим гравцем у квідич, йому вдалося влучити Бладжером шість разів у Квідичних сценах',
      'Вони єдині брати Візлі, які не стають префектами',
      'Одружився з Анджеліною Джонсон після Другої чарівної війни. У них було двоє дітей',
    ],
  },
  {
    name: 'Ромільда Вейн',
    portrait: '',
    house: 'Ґрифіндор',
    description: 'Однокурсниця Гаррі',
    interestingFacts: [
      'Була одержимо закохана в Гаррі Поттера і заздрила його близьким стосункам з друзями',
      'Схоже, вона втілює всі стереотипні аспекти дому Ґрифіндор, як позитивні, так і негативні',
      'Має музичну скриньку з балетним тролем',
      'Про її особистість у фільмах нічого не відомо частково через те, що вона не має реплік у жодному з фільмів, у яких вона з`являється',
    ],
  },
  {
    name: 'Захаріас Сміт',
    portrait: '',
    house: 'Гафелпаф',
    description: 'Однокурсник Гаррі',
    interestingFacts: [
      'Сортувальний капелюх відчув, що Сміт не має жодної з якостей, необхідних для інших будинків, і запропонував йому за замовчуванням Гафелпаф, оскільки Гелґа Гафелпаф брала студентів, яких не вибрали інші засновники',
      'Захаріас Сміт здається приємнішим у кіно, ніж у романах',
      'Герміона думала запросити Сміта на різдвяну вечірку до Слизорога замість Кормака МакЛаггена, оскільки знала, що Рон ненавидить обох хлопців',
    ],
  },
  {
    name: 'Лі Джордан',
    portrait: '',
    house: 'Ґрифіндор',
    description: 'Учень на два роки старше Гаррі',
    interestingFacts: [
      'Лі був жартівником і часто говорив з гумором, чим дуже дратував професорку Макґонеґел, яка була збентежена його коментарями ігор у Квідич',
      'Після закінчення Гоґвортсу він вів радіошоу «Поттервотч», щоб інформувати та підбадьорювати чарівний світ, давав поради, як їх можна захиститися від Волдеморта',
    ],
  },
  {
    name: 'Марієтта Еджком',
    portrait: '',
    house: 'Рейвенклов',
    description: 'Учениця на рік старше Гаррі',
    interestingFacts: [
      'Її мати була службовцем міністерства, і тому Марієтта відчувала сильний тиск, який спонукав її бути бути на боці Амбридж',
      'Після того, як її покарали за зраду Дамблдорової армії, на її обличчі з’явилися прищі у формі напису «ЯБЕДА»',
      'В екранізації Марієтта відсутня, а «зрадницею» є Чо Чанґ, будучи під дією Сироватки правди',
    ],
  },
  {
    name: 'Колін Кріві',
    portrait: '',
    house: 'Ґрифіндор',
    description: 'Учень на рік молодше Гаррі',
    interestingFacts: [
      'Він завжди робив фото під час першого року навчання, що часто набридало всім навколо. Частково це ставалося через те, що він робив фото незручних ситуацій, котрі мали б залишитися приватними',
      'Протягом першого року в Гоґвортсі, хоча вони з Гаррі не були настільки близькі, Колін вважав себе найкращим другом Гаррі',
    ],
  },
];
